<xs:schema
  xmlns="http://rest.immobilienscout24.de/schema/offer/realestateproject/1.0"
  targetNamespace="http://rest.immobilienscout24.de/schema/offer/realestateproject/1.0"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:common="http://rest.immobilienscout24.de/schema/common/1.0"
  elementFormDefault="unqualified"
  attributeFormDefault="unqualified"
  version="1.0">

  <xs:import namespace="http://www.w3.org/1999/xlink"/>
  <xs:import namespace="http://rest.immobilienscout24.de/schema/common/1.0"/>

  <xs:element name="realEstateProjects" type="RealEstateProjects">
    <xs:annotation>
      <xs:documentation xml:lang="en">list of the real estate projects</xs:documentation>
      <xs:documentation xml:lang="de-DE">Bauprojekteliste</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="realEstateProject" type="RealEstateProject">
    <xs:annotation>
      <xs:documentation xml:lang="en">real estate project</xs:documentation>
      <xs:documentation xml:lang="de-DE">Realestateproject</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="realEstateProjectEntries" type="RealEstateProjectEntries">
    <xs:annotation>
      <xs:documentation xml:lang="en">list of the real estate project entry</xs:documentation>
      <xs:documentation xml:lang="de-DE">Realestateprojekteintragsliste</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="realEstateProjectEntry" type="RealEstateProjectEntry">
    <xs:annotation>
      <xs:documentation xml:lang="en">real estate project entry</xs:documentation>
      <xs:documentation xml:lang="de-DE">Realestateprojekteintrag</xs:documentation>
    </xs:annotation>
  </xs:element>


  <xs:complexType name="RealEstateProject">
    <xs:annotation>
      <xs:documentation xml:lang="en">realestateproject</xs:documentation>
      <xs:documentation xml:lang="de-DE">realestateproject</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="1">
      </xs:element>
      <xs:element name="title" type="xs:string" minOccurs="1">
      </xs:element>
      <xs:element name="price" type="common:PriceRangeMandatory" minOccurs="1">
      </xs:element>
      <xs:element name="space" type="common:AreaRangeMandatory" minOccurs="1">
      </xs:element>
      <xs:element name="minPriceProQm" type="common:Number13.2Type" minOccurs="0"/>
      <xs:element name="numberOfHousingUnit" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="9999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="interiorQuality" type="common:InteriorQuality" minOccurs="1">
      </xs:element>
      <xs:element name="freeFrom" type="xs:string"/>
      <xs:element name="address" type="common:Address"/>
      <xs:element name="homepageUrl" type="common:uri" minOccurs="0"/>
      <xs:element name="extProjectUrl" type="common:uri" minOccurs="0"/>
      <xs:element name="customization" type="Customization" minOccurs="0"/>
      <xs:element name="enabledContactFormFields" type="contactFormFields" minOccurs="0"/>
      <xs:element name="referenceNumber" type="xs:string" minOccurs="0" />
      <xs:element name="showroom" type="common:Address" minOccurs="0" />
      <xs:element name="salesProgress" type="percentType" minOccurs="0"/>
      <xs:element name="description" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3000"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="numberOfHousingUnitsDetails" type="NumberOfHousingUnitsDetails" minOccurs="0"/>
      <xs:element name="interiorCharacteristics" type="InteriorCharacteristics" minOccurs="0"/>
      <xs:element name="interiorQualityDescription" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="250"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="locationDescription" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2050"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="rooms" type="NumberOfRoomsRange" minOccurs="0"/>
      <xs:element name="companyName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="100"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="contact" type="Contact" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:long" use="optional">
      <xs:annotation>
        <xs:documentation xml:lang="en">Id of entity entry.</xs:documentation>
        <xs:documentation xml:lang="de-DE">Id des Elements.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="RealEstateProjects">
    <xs:annotation>
      <xs:documentation xml:lang="en">List of real estate projects</xs:documentation>
      <xs:documentation xml:lang="de-DE">Liste von Bauprojekte</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="realEstateProject" type="RealEstateProject" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation xml:lang="en">an real estate project</xs:documentation>
          <xs:documentation xml:lang="de-DE">Bauprojekt</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="RealEstateProjectEntries">
    <xs:annotation>
      <xs:documentation xml:lang="en">List of Realestateproject-Entries</xs:documentation>
      <xs:documentation xml:lang="de-DE">Liste von Realestateprojectseinträgen</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="realEstateProjectEntry" type="RealEstateProjectEntry" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation xml:lang="en">an real estate project entry</xs:documentation>
          <xs:documentation xml:lang="de-DE">Eintrag eines RealEstateprojektes</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute ref="xlink:href">
      <xs:annotation>
        <xs:documentation xml:lang="en">Link to request the list of entries.</xs:documentation>
        <xs:documentation xml:lang="de-DE">Link zum Abruf der Eintragsliste.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="RealEstateProjectEntry">
    <xs:annotation>
      <xs:documentation xml:lang="en">realestateproject entry.</xs:documentation>
      <xs:documentation xml:lang="de-DE">Eintrag in Realestate-Project</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="messageCode" type="xs:string" minOccurs="0" maxOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="en">result of the operation</xs:documentation>
          <xs:documentation xml:lang="de-DE">Realestateprojekteintrag-Ergebnis</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="message" type="xs:string" minOccurs="0" maxOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="en">result of the operation</xs:documentation>
          <xs:documentation xml:lang="de-DE">Realestateprojekteintrag-Ergebnis</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="realEstateId" type="xs:long" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="en">Id of realestate.</xs:documentation>
          <xs:documentation xml:lang="de-DE">Id des Immobilienobjektes.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="realEstateExternalId" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="en">Id of realestate.</xs:documentation>
          <xs:documentation xml:lang="de-DE">Id des Immobilienobjektes.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:long" use="optional">
      <xs:annotation>
        <xs:documentation xml:lang="en">Id of entity entry.</xs:documentation>
        <xs:documentation xml:lang="de-DE">Id des Elements.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>


  <xs:complexType name="Attachment" abstract="true">
    <xs:annotation>
      <xs:documentation xml:lang="en">An attachment.</xs:documentation>
      <xs:documentation xml:lang="de-DE">Ein Anhang.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="id" type="xs:string">
      <xs:annotation>
        <xs:documentation xml:lang="en">Id of Attachment.</xs:documentation>
        <xs:documentation xml:lang="de-DE">ID des Anhangs.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:element name="attachment" type="Attachment"/>


  <xs:complexType name="Attachments">
    <xs:annotation>
      <xs:documentation xml:lang="en">List of Attachments.</xs:documentation>
      <xs:documentation xml:lang="de-DE">Liste von Anhängen.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="attachment" type="Attachment" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="attachments" type="Attachments"/>


  <xs:complexType name="PDFDocument">
    <xs:annotation>
      <xs:documentation xml:lang="en">A pdf document.</xs:documentation>
      <xs:documentation xml:lang="de-DE">Ein PDF-Dokument.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="Attachment">
        <xs:sequence>
          <xs:element name="url" type="common:uri" minOccurs="0"/>
          <xs:element name="pdfDocumentType" type="PDFDocumentType"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="PDFDocumentType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BROCHURE"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="Picture">
    <xs:annotation>
      <xs:documentation xml:lang="en">A picture.</xs:documentation>
      <xs:documentation xml:lang="de-DE">Ein Bild.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="Attachment">
        <xs:sequence>
          <xs:element name="pictureType" type="PictureType"/>
          <xs:element name="title" minOccurs="0">
            <xs:simpleType>
              <xs:restriction base="common:TextField">
                <xs:minLength value="3"/>
                <xs:maxLength value="100"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="urls" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="url" maxOccurs="unbounded">
                  <xs:annotation>
                    <xs:documentation xml:lang="en">URL of the picture.</xs:documentation>
                    <xs:documentation xml:lang="de-DE">URL des Bildes.</xs:documentation>
                  </xs:annotation>
                  <xs:complexType>
                    <xs:attribute name="scale" type="common:PictureScaleType">
                      <xs:annotation>
                        <xs:documentation xml:lang="en">Picture scale.</xs:documentation>
                        <xs:documentation xml:lang="de-DE">Bildergröße.</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="href" type="xs:string">
                      <xs:annotation>
                        <xs:documentation xml:lang="en">URL to scaled picture.</xs:documentation>
                        <xs:documentation xml:lang="de-DE">URL zum skaliertem Bild.</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="PictureType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="COMPANY_LOGO"/>
      <xs:enumeration value="PROJECT_LOGO"/>
      <xs:enumeration value="IMAGE"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="Link">
    <xs:annotation>
      <xs:documentation xml:lang="en">Link to external resource.</xs:documentation>
      <xs:documentation xml:lang="de-DE">Ein Verweis zu einer externen Ressource.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="Attachment">
        <xs:sequence>
          <xs:element name="url" type="common:uri"/>
          <xs:element name="linkType" type="LinkType"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="LinkType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="VIRTUAL_TOUR"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="AttachmentsOrder">
    <xs:sequence>
      <xs:element name="attachmentId" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="attachmentsOrder" type="AttachmentsOrder"/>


  <xs:complexType name="UploadTicketRequest">
    <xs:sequence>
      <xs:element name="attachmentContentType" type="AttachmentContentType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="AttachmentContentType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="image/jpeg"/>
      <xs:enumeration value="image/png"/>
      <xs:enumeration value="image/gif"/>
      <xs:enumeration value="image/svg+xml"/>
      <xs:enumeration value="application/pdf"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="uploadTicketRequest" type="UploadTicketRequest"/>


  <xs:complexType name="UploadTicket">
    <xs:sequence>
      <xs:element name="url" type="common:uri"/>
      <xs:element name="attachmentId" type="xs:string"/>
      <xs:element name="fields">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="field" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="key" type="xs:string"/>
                <xs:attribute name="value" type="xs:string"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="uploadTicket" type="UploadTicket"/>


  <xs:complexType name="ProjectProposal">
    <xs:sequence>
      <xs:element name="customerName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="80"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="companyName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="100"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="email" type="common:Email"/>
      <xs:element name="phoneNumber">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="40"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="projectName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="40"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="postcode">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="city">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="startDate" type="xs:date"/>
      <xs:element name="numberOfHousingUnits">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="9999"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="externalId">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="100"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="crmName" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="en">Name of the CRM</xs:documentation>
          <xs:documentation xml:lang="de-DE">Name des CRM</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="80"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="projectProposal" type="ProjectProposal"/>


  <xs:complexType name="InteriorCharacteristics">
    <xs:sequence minOccurs="3" maxOccurs="20">
      <xs:element name="InteriorCharacteristic">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="100"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Contact">
    <xs:sequence>
      <xs:element name="lastName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="firstName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="30"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="email" type="common:Email"/>
      <xs:element name="phone">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="40"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="NumberOfRoomsRange">
    <xs:annotation>
      <xs:documentation xml:lang="en">number of rooms range</xs:documentation>
      <xs:documentation xml:lang="de-DE">Bereich der Zimmeranzahl</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="minimal" type="NumberOfRoomsType" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="en">minimal number of rooms</xs:documentation>
          <xs:documentation xml:lang="de-DE">Minimale Anzahl der Räume</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="maximal" type="NumberOfRoomsType" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="en">maximal number of rooms</xs:documentation>
          <xs:documentation xml:lang="de-DE">Maximale Anzahl der Räume</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:simpleType name="NumberOfRoomsType">
    <xs:annotation>
      <xs:documentation xml:lang="en">number of room type for validation</xs:documentation>
      <xs:documentation xml:lang="de-DE">Anzahl Räume Typ zur Validierung</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:decimal">
      <xs:totalDigits value="5" fixed="true"/>
      <xs:fractionDigits value="1" fixed="true"/>
      <xs:minInclusive value="1" fixed="true"/>
      <xs:maxInclusive value="9999" fixed="true"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="NumberOfHousingUnitsDetails">
    <xs:sequence>
      <xs:element name="apartmentCount" type="xs:int"/>
      <xs:element name="houseCount" type="xs:int"/>
      <xs:element name="commercialCount" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Customization">
    <xs:sequence>
      <xs:element name="layoutColor" minOccurs="0">
        <xs:simpleType>
          <xs:restriction  base="xs:string">
            <xs:pattern value="#(([0-9]|[a-f]){3}|([0-9]|[a-f]){6})"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="announcement" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="500"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="percentType">
    <xs:restriction base="xs:int">
      <xs:enumeration value="0"/>
      <xs:enumeration value="10"/>
      <xs:enumeration value="20"/>
      <xs:enumeration value="30"/>
      <xs:enumeration value="40"/>
      <xs:enumeration value="50"/>
      <xs:enumeration value="60"/>
      <xs:enumeration value="70"/>
      <xs:enumeration value="80"/>
      <xs:enumeration value="90"/>
      <xs:enumeration value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="contactFormFields">
    <xs:sequence>
      <xs:element name="firstName" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="en">whether enable first name in the contact form
          </xs:documentation>
          <xs:documentation xml:lang="de-DE">ob Vorname im Kontaktformular aktiviert ist
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="address" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="en">whether enable address in the contact form
          </xs:documentation>
          <xs:documentation xml:lang="de-DE">ob Adresse im Kontaktformular aktivieren
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="phone" type="xs:boolean" minOccurs="0">
        <xs:annotation>
          <xs:documentation xml:lang="en">whether enable phone in the contact form
          </xs:documentation>
          <xs:documentation xml:lang="de-DE">ob Telefon im Kontaktformular aktiviert ist
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
